### ISSUE TITLE
Stable Version Wanted.

### ISSUE THREAD

**Issue by MiaoDX** [abhineet123/MTF#12]
Hei, 

This work looks charming, I am wondering however, could it be possible to have some stable version so that I can use it in my own project? It's awesome to see that the project is evolving all the time, but always changing (may) also means possible bugs here and there. 

Thanks.

**Comment by abhineet123** [comment]
The core modules (SMs, AMs, SSMs, ILMs and core Utils) haven't changed for a while now. All of the recent commits have been either improvements to the examples and readme or additions/bug fixes to third party and other optional modules for better compatibility with OpenCV 3.3 and 3.4.
There hasn't been a stable release yet because we haven't had enough testers for MTF so we don't know if it is sufficiently bug-free for such a release. We are now using it for a course so hopefully this problem will soon be resolved as students start using it for their coursework and so subject it to extensive testing.

**Comment by MiaoDX** [comment]
Yeah, successed in running on WIN10 with the `towel sequence from LinTrack dataset`, looking forward for the fully OpenCV 3.x (and maybe python3?) integration. I will close this issue now.
